"use client"
import './globals.css'
import { useState } from 'react'
import Footer from './Footer'




const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({ children }) {

  const [open, setOpen] = useState(false);


  return (
    <html lang="en">
      <head>
        {/* font asowome */}
        <script src="https://kit.fontawesome.com/90623e284f.js" crossOrigin="anonymous"></script>
        {/* google font  */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="stylesheet" href="https://rafusoft.com/assets/frontend/css/style.css" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='true' />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet"></link>
      </head>
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  )
}





